import Sequelize, { Model } from 'sequelize';

export default sequelize =>
    class Operador2 extends Model {
        static init() {
            super.init(
                {
                    operador_id: Sequelize.INTEGER,
                    cad_motivonc_ac: Sequelize.NUMBER,
                    cad_motivonc_ad: Sequelize.NUMBER,
                    cad_motivonc_md: Sequelize.NUMBER,
                    cad_motivonc_co: Sequelize.NUMBER,
                    cad_motivonc_ex: Sequelize.NUMBER,
                    cad_apoio_co: Sequelize.NUMBER,
                    cad_situacao_co: Sequelize.NUMBER,
                    cad_cartao_co: Sequelize.NUMBER,
                    cad_banco_co: Sequelize.NUMBER,
                    cad_forpag_co: Sequelize.NUMBER,
                    cad_nc_ac: Sequelize.NUMBER,
                    cad_nc_ad: Sequelize.NUMBER,
                    cad_nc_md: Sequelize.NUMBER,
                    cad_nc_co: Sequelize.NUMBER,
                    cad_nc_ex: Sequelize.NUMBER,
                    cad_filtro_ad: Sequelize.NUMBER,
                    cad_filtro_md: Sequelize.NUMBER,
                    cad_filtro_co: Sequelize.NUMBER,
                    cad_filtro_ex: Sequelize.NUMBER,
                    cad_questao_ac: Sequelize.NUMBER,
                    cad_questao_ad: Sequelize.NUMBER,
                    cad_questao_md: Sequelize.NUMBER,
                    cad_questao_co: Sequelize.NUMBER,
                    cad_questao_ex: Sequelize.NUMBER,
                    cad_eqp_ac: Sequelize.NUMBER,
                    cad_eqp_ad: Sequelize.NUMBER,
                    cad_eqp_md: Sequelize.NUMBER,
                    cad_eqp_co: Sequelize.NUMBER,
                    cad_eqp_ex: Sequelize.NUMBER,
                    cad_empresa_ac: Sequelize.NUMBER,
                    cad_empresa_ad: Sequelize.NUMBER,
                    cad_empresa_md: Sequelize.NUMBER,
                    cad_empresa_co: Sequelize.NUMBER,
                    cad_empresa_ex: Sequelize.NUMBER,
                    naolancares: Sequelize.NUMBER,
                    naovoltastatus: Sequelize.NUMBER,
                    reabre_caixa: Sequelize.NUMBER,
                    altera_caixa: Sequelize.NUMBER,
                    relcaixa_geral: Sequelize.NUMBER,
                    nao_reimprime_exa: Sequelize.NUMBER,
                    nao_libera_exa: Sequelize.NUMBER,
                    acessa_propriocaixa: Sequelize.NUMBER,
                    cad_req_ad: Sequelize.NUMBER,
                    cad_req_md: Sequelize.NUMBER,
                    cad_req_co: Sequelize.NUMBER,
                    cad_req_ex: Sequelize.NUMBER,
                    cad_req_ac: Sequelize.NUMBER,
                    vis_custoatend: Sequelize.NUMBER,
                    recalcula_custo: Sequelize.NUMBER,
                    cad_linha_ad: Sequelize.NUMBER,
                    cad_linha_md: Sequelize.NUMBER,
                    cad_linha_co: Sequelize.NUMBER,
                    cad_linha_ex: Sequelize.NUMBER,
                    cad_linha_ac: Sequelize.NUMBER,
                    faturamentomed: Sequelize.NUMBER,
                    sofatura: Sequelize.NUMBER,
                    geratiss: Sequelize.NUMBER,
                    fatsusbpa: Sequelize.NUMBER,
                    visu_exa_lib: Sequelize.NUMBER,
                    estposcol: Sequelize.NUMBER,
                    estposexa: Sequelize.NUMBER,
                    estconv: Sequelize.NUMBER,
                    estmedicos: Sequelize.NUMBER,
                    estsetor: Sequelize.NUMBER,
                    estenvio: Sequelize.NUMBER,
                    estopera: Sequelize.NUMBER,
                    estgrafico: Sequelize.NUMBER,
                    estlibexa: Sequelize.NUMBER,
                    estposprontu: Sequelize.NUMBER,
                    conffat: Sequelize.NUMBER,
                    repete_exa: Sequelize.NUMBER,
                    cad_medicorea_ac: Sequelize.NUMBER,
                    cad_medicorea_ad: Sequelize.NUMBER,
                    cad_medicorea_md: Sequelize.NUMBER,
                    cad_medicorea_co: Sequelize.NUMBER,
                    cad_medicorea_ex: Sequelize.NUMBER,
                    caixa_desc: Sequelize.NUMBER,
                    estentrega: Sequelize.NUMBER,
                    reldesc: Sequelize.NUMBER,
                    caixaperm: Sequelize.STRING,
                    etqultpacperm: Sequelize.NUMBER,
                    del_fu_fm: Sequelize.NUMBER,
                    desabilita_naofatura: Sequelize.NUMBER,
                    nao_altera_pac_triado: Sequelize.NUMBER,
                    visuetqinter: Sequelize.NUMBER,
                    nao_altera_material_exa: Sequelize.NUMBER,
                    coleta_material: Sequelize.NUMBER,
                    env_malote_material: Sequelize.NUMBER,
                    descoleta_material: Sequelize.NUMBER,
                    imprime_tabela: Sequelize.NUMBER,
                    assinatura_bmp: Sequelize.TEXT,
                    nao_alt_conv_atend: Sequelize.NUMBER,
                    cad_plano_ac: Sequelize.NUMBER,
                    cad_plano_ad: Sequelize.NUMBER,
                    cad_plano_md: Sequelize.NUMBER,
                    cad_plano_co: Sequelize.NUMBER,
                    cad_plano_ex: Sequelize.NUMBER,
                    data_ent: Sequelize.NUMBER,
                    rps_nfe: Sequelize.NUMBER,
                    idopera_ultacao: Sequelize.INTEGER,
                    perm_etq_opera: Sequelize.NUMBER,
                    bi: Sequelize.NUMBER,
                    altresgrad: Sequelize.NUMBER,
                    nao_alt_dtentrega: Sequelize.NUMBER,
                    filtro_situacao_perm: Sequelize.STRING,
                    bloqexame: Sequelize.STRING,
                    cad_interfere_co: Sequelize.NUMBER,
                    cad_matmed_co: Sequelize.NUMBER,
                    cad_setor_co: Sequelize.NUMBER,
                    acessa_painel_cli: Sequelize.NUMBER,
                },
                {
                    sequelize,
                    tableName: 'operador2',
                    timestamps: false,
                }
            );

            return this;
        }

        // associacao tabela operador
        static associate(models) {
            this.belongsTo(models.Operador, {
                foreignKey: 'id',
                as: 'operador',
            });
        }
    };
