import Sequelize, { Model } from 'sequelize';

export default sequelize =>
    class Paramf extends Model {
        static init() {
            super.init(
                {
                    corfundo: Sequelize.NUMBER,
                    papelfundo: Sequelize.STRING,
                    landpto: Sequelize.NUMBER,
                    razao: Sequelize.STRING,
                    cnpj: Sequelize.STRING,
                    endereco: Sequelize.STRING,
                    cidade: Sequelize.STRING,
                    bairro: Sequelize.STRING,
                    uf: Sequelize.STRING,
                    cep: Sequelize.STRING,
                    tel: Sequelize.STRING,
                    email: Sequelize.STRING,
                    responsavel: Sequelize.STRING,
                    com_easyvet: Sequelize.NUMBER,
                    libpag: Sequelize.NUMBER,
                    datlic: Sequelize.DATE,
                    contas_id: Sequelize.INTEGER,
                    desccontas: Sequelize.STRING,
                    sacado_id: Sequelize.INTEGER,
                    descsacado: Sequelize.STRING,
                    descfornec: Sequelize.STRING,
                    fornec_id: Sequelize.INTEGER,
                    nf: Sequelize.NUMBER,
                    descir: Sequelize.NUMBER,
                    descpis: Sequelize.NUMBER,
                    desccofins: Sequelize.NUMBER,
                    desccssl: Sequelize.NUMBER,
                    percir: Sequelize.NUMBER,
                    percpis: Sequelize.NUMBER,
                    perccofins: Sequelize.NUMBER,
                    perccssl: Sequelize.NUMBER,
                    minimo: Sequelize.NUMBER,
                    percret: Sequelize.NUMBER,
                    perciss: Sequelize.NUMBER,
                    minimo1: Sequelize.NUMBER,
                    fortri_id: Sequelize.INTEGER,
                    descfortri: Sequelize.STRING,
                    bantri_id: Sequelize.INTEGER,
                    descbantri: Sequelize.STRING,
                    centri_id: Sequelize.INTEGER,
                    desccentri: Sequelize.STRING,
                    plirtri_id: Sequelize.INTEGER,
                    descplirtri: Sequelize.STRING,
                    plcssltri_id: Sequelize.INTEGER,
                    descplcssltri: Sequelize.STRING,
                    formes_id: Sequelize.INTEGER,
                    descformes: Sequelize.STRING,
                    banmes_id: Sequelize.INTEGER,
                    descbanmes: Sequelize.STRING,
                    cenmes_id: Sequelize.INTEGER,
                    desccenmes: Sequelize.STRING,
                    plpismes_id: Sequelize.INTEGER,
                    descplpismes: Sequelize.STRING,
                    plcofinsmes_id: Sequelize.INTEGER,
                    descplcofinsmes: Sequelize.STRING,
                    pladtri_id: Sequelize.INTEGER,
                    descpladtri: Sequelize.STRING,
                    plissmes_id: Sequelize.INTEGER,
                    descplissmes: Sequelize.STRING,
                    percdarfs: Sequelize.NUMBER,
                    atupg: Sequelize.NUMBER,
                    formesiss_id: Sequelize.INTEGER,
                    descformesiss: Sequelize.STRING,
                    nossonumero: Sequelize.STRING,
                    focoemissao: Sequelize.NUMBER,
                    trazrec: Sequelize.NUMBER,
                    gerap: Sequelize.NUMBER,
                    trazrem: Sequelize.NUMBER,
                    exibenf: Sequelize.NUMBER,
                    retdatocorre: Sequelize.NUMBER,
                    filrec: Sequelize.NUMBER,
                    trazrecdt: Sequelize.NUMBER,
                    impetqbol: Sequelize.NUMBER,
                    emailbol: Sequelize.NUMBER,
                    ccustolc_id: Sequelize.INTEGER,
                    desccustolc: Sequelize.STRING,
                    plcontaslc_id: Sequelize.INTEGER,
                    descplcontaslc: Sequelize.STRING,
                    ccustonf_id: Sequelize.INTEGER,
                    desccustonf: Sequelize.STRING,
                    plcontasnf_id: Sequelize.INTEGER,
                    descplcontasnf: Sequelize.STRING,
                    emp_id: Sequelize.INTEGER,
                    descemp: Sequelize.STRING,
                    usaemp: Sequelize.NUMBER,
                    focoemp: Sequelize.NUMBER,
                    obsnf: Sequelize.NUMBER,
                    cadsb: Sequelize.NUMBER,
                    nfmanual: Sequelize.NUMBER,
                    trazrecdte: Sequelize.NUMBER,
                    usaissemp: Sequelize.NUMBER,
                    focoaf: Sequelize.NUMBER,
                    trazab: Sequelize.NUMBER,
                    subimprec: Sequelize.NUMBER,
                    datarecebe: Sequelize.NUMBER,
                    verifdow: Sequelize.NUMBER,
                    contasr_id: Sequelize.INTEGER,
                    desccontasr: Sequelize.STRING,
                    ccustor_id: Sequelize.INTEGER,
                    desccustor: Sequelize.STRING,
                    plcontasr_id: Sequelize.INTEGER,
                    descplcontasr: Sequelize.STRING,
                    naousapainel: Sequelize.NUMBER,
                    bancodin_id: Sequelize.INTEGER,
                    bancochv_id: Sequelize.INTEGER,
                    bancochp_id: Sequelize.INTEGER,
                    bancoctd_id: Sequelize.INTEGER,
                    bancoctc_id: Sequelize.INTEGER,
                    bancoout_id: Sequelize.INTEGER,
                    plcontasdin_id: Sequelize.INTEGER,
                    plcontaschv_id: Sequelize.INTEGER,
                    plcontaschp_id: Sequelize.INTEGER,
                    plcontasctd_id: Sequelize.INTEGER,
                    plcontasctc_id: Sequelize.INTEGER,
                    plcontasout_id: Sequelize.INTEGER,
                    desciss: Sequelize.NUMBER,
                    sacrec_id: Sequelize.INTEGER,
                    descsacrec: Sequelize.STRING,
                    nbreqneg: Sequelize.NUMBER,
                    major_fin: Sequelize.NUMBER,
                    minor_fin: Sequelize.NUMBER,
                    rev_fin: Sequelize.NUMBER,
                    maiori: Sequelize.NUMBER,
                    menori: Sequelize.NUMBER,
                    maiort: Sequelize.STRING,
                    entret: Sequelize.STRING,
                    menort: Sequelize.STRING,
                    descbol: Sequelize.NUMBER,
                    mostravalid: Sequelize.NUMBER,
                    validade: Sequelize.NUMBER,
                    usaquali: Sequelize.NUMBER,
                    libcot: Sequelize.NUMBER,
                    descirp: Sequelize.NUMBER,
                    descpisp: Sequelize.NUMBER,
                    desccofinsp: Sequelize.NUMBER,
                    desccsslp: Sequelize.NUMBER,
                    descissp: Sequelize.NUMBER,
                    idopera_ultacao: Sequelize.INTEGER,
                    libped: Sequelize.NUMBER,
                    painel_estmin: Sequelize.NUMBER,
                    dtent_fechcaixa: Sequelize.NUMBER,
                },
                {
                    sequelize,
                    modelName: 'Paramf',
                    tableName: 'paramf',
                    timestamps: false,
                }
            );
            return this;
        }

        static associate(models) {
            this.belongsTo(models.Contas, {
                foreignKey: 'bancodin_id',
                as: 'bancodin',
            });
            this.belongsTo(models.Contas, {
                foreignKey: 'bancochv_id',
                as: 'bancochv',
            });
            this.belongsTo(models.Contas, {
                foreignKey: 'bancochp_id',
                as: 'bancochp',
            });
            this.belongsTo(models.Contas, {
                foreignKey: 'bancoctd_id',
                as: 'bancoctd',
            });
            this.belongsTo(models.Contas, {
                foreignKey: 'bancoctc_id',
                as: 'bancoctc',
            });
            this.belongsTo(models.Contas, {
                foreignKey: 'bancoout_id',
                as: 'bancoout',
            });
            this.belongsTo(models.Plcontas, {
                foreignKey: 'plcontasdin_id',
                as: 'plcontasdin',
            });
            this.belongsTo(models.Plcontas, {
                foreignKey: 'plcontaschv_id',
                as: 'plcontaschv',
            });
            this.belongsTo(models.Plcontas, {
                foreignKey: 'plcontaschp_id',
                as: 'plcontaschp',
            });
            this.belongsTo(models.Plcontas, {
                foreignKey: 'plcontasctd_id',
                as: 'plcontasctd',
            });
            this.belongsTo(models.Plcontas, {
                foreignKey: 'plcontasctc_id',
                as: 'plcontasctc',
            });
            this.belongsTo(models.Plcontas, {
                foreignKey: 'plcontasout_id',
                as: 'plcontasout',
            });
        }
    };
